Feature/preload callbacks
DylanVann/react-native-fast-image pull request #437
Opened 2019-03-26 17:26 UTC by Mickagd

We also need this PR to be merged

2019-03-27 06:39 UTC, guhungry requested changes
Please rename `FastImagePreloaderModule` back to `FastImageViewModule` and extract method into new class instead from preload()

2019-03-27 06:39 UTC, guhungry commented on android/src/main/java/com/dylanvann/fastimage/FastImagePreloaderModule.java
> +class FastImagePreloaderModule extends ReactContextBaseJavaModule {
Why rename class just like that. I have #425 which edit FastImageViewModule.java

2019-05-13 15:21 UTC, RWOverdijk commented
Hey all! Is this going somewhere?

2019-05-17 18:40 UTC, augustbjornberg commented
Is this PR still being worked on? Would be such a nice feature to have.

2019-05-28 14:50 UTC, Ilphrin commented
There are some conflicts, I think you should resolve them @Mickagd before @DylanVann can take a look at this PR ^^

2019-06-12 09:54 UTC, SamiChab commented
Please consider implementing this! It would be so useful!

2019-06-19 11:52 UTC, RWOverdijk commented
Really happy to see this still moving forward! I can't wait to remove my component hack 😄

2019-08-21 00:56 UTC, LuisRodriguezLD commented
Hello. Any update on this?

2019-08-21 05:46 UTC, RWOverdijk commented
@LuisRodriguezLD As far as I can see there are conflicts.

2019-10-12 08:59 UTC, RWOverdijk commented
I've reimplemented this. Confirmed to work on iOS. Android I'll check later. I'll make a PR when I'm done.

On a sidenote, my solution uses a lot less code so I'm hoping that makes it easier to get it merged.

2019-10-15 16:52 UTC, joan-saum commented
@RWOverdijk can you reference your PR?

2019-10-15 16:54 UTC, Elindorath commented
Hi @RWOverdijk. Thanks for your work! Could you publish your reimplementation on your fork that we can help to test it and speed up this to get it merged?

We really need this to be compatible with RN v0.60+.

2019-10-15 17:06 UTC, RWOverdijk commented
@Elindorath Sure thing. I have to finish android first though. The module is compatioble with 0.60+ for me, so I'm not sure what you mean

2019-11-04 11:02 UTC, joan-saum commented
Hi @RWOverdijk , how is it going with Android ? :) Need any help ?

2019-11-05 12:32 UTC, sebinq commented
Promise should also return which pictures from array couldn't be fetched, not only how many couldn't be fetched.

2019-11-05 13:22 UTC, RWOverdijk commented
@joan-saum It's going all right. The biggest problem right now is time and priorities. I can push the iOS stuff at some point this or next week though, maybe someone else can then PR the android stuff to my branch and we can get this thing going!

Sorry for my lack of time... It bothers me as well.

2019-11-11 08:49 UTC, sebinq commented
Please, consider to also add id to every image, so we can check from react-native side which images failed to load.

2019-11-11 10:22 UTC, RWOverdijk commented
@sebinq I will not be doing that but you could add that after if you want.

2019-11-11 10:23 UTC, sebinq commented
@RWOverdijk thanks for info,, I will try.

2019-12-02 10:11 UTC, joan-saum commented
@RWOverdijk are you still working on it ?
If you did the iOS part, don't hesitate to open a PR so we can work on the Android side
Just let me know so I can know if I should just wait or work on it !

2019-12-02 10:28 UTC, RWOverdijk commented
@joan-saum https://github.com/RWOverdijk/react-native-fast-image/tree/feat/preload-callbackl

The Android code is nonsense. I will work on it but I don't know when exactly so feel free to PR to that branch and I'll test and PR to this repo.

2019-12-30 14:27 UTC, mainginski commented
Updates?

2020-01-22 19:08 UTC, augustbjornberg commented
I've been hopefully anticipating this feature for over a year now. There's some unfortunate off-putting visual behavior in the apps where i use react-native-fast-image because of it, and i'm guessing i'm not the only one. Implementing preload with no way of knowing when it completed is as near as makes no difference as useful as no preload at all.

Had i the ability and confidence to build this feature myself i would, but i don't. At this point i'd happily pay someone to have a PR with this feature merged.

2020-01-23 08:49 UTC, joan-saum commented
I tried the android side but I don't have enough Java skills to make it or it would take me too much time. For now, I'm using the fork which was used for this PR: https://github.com/DylanVann/react-native-fast-image/pull/268 to have the callback (and it works well). Maybe you should consider doing this @augustbjornberg 

@DylanVann It is pitty this PR has not been merged, even if SDWebImage does not give enough informations (see the conversation in the PR). It could be a great step for everyone who wait for having a callback of the preload.

2020-01-23 08:50 UTC, sebinq commented
I was also trying to implement it but without any success

2020-01-23 08:50 UTC, RWOverdijk commented
The problem is that my project isn't selling well enough to prioritize this feature (My sales strategy was well calculated but man, am I bad at math.).

2020-01-23 18:05 UTC, augustbjornberg commented
Thanks @joan-saum, i'm definitely considering it. Really wish i didn't have to resort to a 5 months old PR though. Would you run [#268](https://github.com/DylanVann/react-native-fast-image/pull/268) in production with 50k active users? I'd be devastated if something went wrong.

2021-08-20 16:02 UTC, Mickagd commented
We have updated our PR with your last changes.
There is a lot of people that need these changes.
Could you please merge this request @DylanVann ?
Thanks a lot  !

2021-08-30 03:39 UTC, nguyenphucbao68 commented
Please merge this PR. I really need it 👍

2022-01-25 13:41 UTC, Flictuum commented
Hi guys just a last call if it's possible to merge this PR, we invested time here to bring last changes to the PR and I think this will help a lot of people.
So I hope my words will find you @DylanVann
Thanks a lot for your work and maybe we could help to maintain this package for other needs !

2022-01-31 14:23 UTC, nicomontanari requested changes

2022-01-31 14:23 UTC, nicomontanari commented on src/index.tsx
> -const FastImageViewNativeModule = NativeModules.FastImageView
This line should remain because it is needed to use "clearMemoryCache" and "clearDiskCache". It also generate a typescript error.

2022-05-20 07:25 UTC, putuoka commented
how to implement this into my project? because i don't have src folder in my node_modules fast image

2022-05-20 08:42 UTC, nicomontanari commented
Hi @putuoka, did you download the stable version of the package or did you download it from this pull request?

If you have downloaded the stable version in your `node_modules` folder you should see the compiled package in the `dist` folder, if not you should see the entire project as the below image:

![Schermata 2022-05-20 alle 10 41 25](https://user-images.githubusercontent.com/15747776/169489938-f7b69f94-2457-4db5-996f-8a3a26957bd6.png)

2022-05-20 09:22 UTC, putuoka commented
> Hi @putuoka, did you download the stable version of the package or did you download it from this pull request?
> 
> If you have downloaded the stable version in your `node_modules` folder you should see the compiled package in the `dist` folder, if not you should see the entire project as the below image:
> 
> ![Schermata 2022-05-20 alle 10 41 25](https://user-images.githubusercontent.com/15747776/169489938-f7b69f94-2457-4db5-996f-8a3a26957bd6.png)

Hi @nicomontanari , thanks for the reply. i have downloaded stable version using ```` yarn add react-native-fast-image````
what i mean is, in this pull request there is 12 files change one of them is ```` PreloaderManager.tsx ```` which i can't find in my node_modules react-native-fast-image

![image](https://user-images.githubusercontent.com/20880839/169497287-8ca5e988-b311-4372-9acd-c4ed597d8b0e.png)

sorry because i'm new with rn i might missing something here. sorry for my english. please enlighten me because i need to use preload promise/callback to know when it done downloading resources and then i can use it as cache with fast images & redux persist

2022-05-20 13:38 UTC, nicomontanari commented
@putuoka you need to install this package with `yarn add DylanVann/react-native-fast-image#pull/437/head` or `npm install DylanVann/react-native-fast-image#pull/437/head` if you use npm

2022-05-23 03:32 UTC, putuoka commented
> @putuoka you need to install this package with `yarn add DylanVann/react-native-fast-image#pull/437/head` or `npm install DylanVann/react-native-fast-image#pull/437/head` if you use npm

Hi @nicomontanari i got this error:

````

error: Error: While trying to resolve module `react-native-fast-image` from file `D:\gcp-app\src\MainApp.js`, the package 
`D:\gcp-app\node_modules\react-native-fast-image\package.json` was successfully found. However, this package itself 
specifies a `main` module field that could not be resolved (`D:\gcp-app\node_modules\react-native-fast-image\dist\index.cjs.js`. 
Indeed, none of these files exist:

````

2022-08-05 11:38 UTC, patissier-boulanger commented
really need this!

2022-10-23 10:41 UTC, knro commented
Any plans yet to merge this? Any forks that have this merged with upstream?

2023-03-22 13:53 UTC, AlessandroAries commented
> Any plans yet to merge this? Any forks that have this merged with upstream?

I added the changes to my fork with the updated stream: https://github.com/DylanVann/react-native-fast-image/pull/986

2023-06-20 11:19 UTC, skizzo commented
This would be so nice to have!

2023-07-07 06:59 UTC, ymc-thzi commented
Had the same need, couldn't patch the PR due to conflicts. I am using another patch to get the [cache folder path](https://github.com/DylanVann/react-native-fast-image/files/9583091/react-native-fast-image%2B8.6.1.patch.zip)
With that I wrote a tiny function to get the state and even a progress of the cached images. Maybe this helps someone as a workaround...

```
  async function checkCacheFolder(cacheFolderPath, expectedImageCount) {
    try {
      const files = await RNFS.readDir(cacheFolderPath);
      const imageCount = files.filter(
        file => file.isFile() && file.name.endsWith('.jpg'),
      ).length;

      if (imageCount === expectedImageCount) {
        console.log('Images cache complete');
        return;
      }

      let progress = (imageCount / expectedImageCount) * 100;
      console.log(progress.toFixed(0));

      setTimeout(() => {
       checkCacheFolder(
          cacheFolderPath,
          expectedImageCount,
        );
      }, 1000);
    } catch (error) {
      //Sentry will log that
    }
  },
```

2023-07-17 09:13 UTC, closed without merging